language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*
  - SYMFONY_VERSION=3.1.*
  - SYMFONY_VERSION=dev-master

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - env: SYMFONY_VERSION=dev-master

sudo: false

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 'nightly' && $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-rm xdebug.ini; fi

install:
  - if [[ $SYMFONY_VERSION == '3.0' ]]; then composer require twig/twig:~1.18 --no-update; fi
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer update --prefer-dist --no-interaction
