language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

env:
  - SYMFONY_VERSION=2.0.*
  - SYMFONY_VERSION=2.1.*
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*
  - SYMFONY_VERSION=dev-master

before_install:
  - composer self-update

install:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer require sensio/framework-extra-bundle:${SYMFONY_VERSION} --no-update
  - composer update --prefer-dist --no-interaction

sudo: false
